export const listadoPaises = [
    'Qatar',
    'Ecuador',
    'Senegal',
    'Netherlands',
    'United Kingdom',
    'Iran',
    'United States',
    'Ukraine',
    'Argentina',
    'Saudi Arabia',
    'Mexico',
    'Poland',
    'France',
    'Peru',
    'Denmark',
    'Tunisia',
    'Spain',
    'Costa Rica',
    'Germany',
    'Japan',
    'Belgium',
    'Canada',
    'Morocco',
    'Croatia',
    'Brazil',
    'Serbia',
    'Switzerland',
    'Cameroon',
    'Portugal',
    'Ghana',
    'Uruguay',
    'North Korea'
]

export const gruposPaises = [
    ['Qatar', 'Ecuador', 'Senegal', 'Netherlands'],
    ['United Kingdom','Iran', 'United States', 'Ukraine'],
    ['Argentina','Saudi Arabia','Mexico', 'Poland'],
    ['France','Peru','Denmark','Tunisia'],
    ['Spain','Costa Rica','Germany','Japan'],
    ['Belgium','Canada','Morocco','Croatia'],
    ['Brazil','Serbia','Switzerland','Cameroon'],
    ['Portugal','Ghana','Uruguay','North Korea']
]